=== codehaus/dentaku/dentaku-cartridge-generator/src/xml/gengenMapping.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--W3C Schema generated by XML Spy v4.2 U (http://www.xmlspy.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="mapping">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="element" type="elementType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="stereotype" type="stereotypeType" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="tagNameBase" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="elementType">
		<xs:sequence>
			<xs:element name="location" ref="location" minOccurs="1" maxOccurs="unbounded"/>
			<xs:element name="stereotype" type="stereotypeType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="path" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:complexType name="generatorType">
		<xs:attribute name="canonicalName" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:element name="location">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="root"/>
				<xs:enumeration value="package"/>
				<xs:enumeration value="class"/>
				<xs:enumeration value="method"/>
				<xs:enumeration value="field"/>
				<xs:enumeration value="relation"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:complexType name="stereotypeType">
		<xs:sequence>
			<xs:element name="generator" type="generatorType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" use="required" />
	</xs:complexType>
</xs:schema>

=== codehaus/dentaku/dentaku-cartridge-generator/src/xml/mapping.xml
<?xml version="1.0" encoding="UTF-8"?>
<mapping tagNameBase="org.dentaku.gentaku.jdo" xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="gengenMapping.xsd">
	<element path="/xs:schema/xs:element[@name='jdo']" location="root"/>
	<element path="/xs:schema/xs:element[@name='package']" location="package">
		<stereotype name="Package"/>
	</element>
	<element path="/xs:schema/xs:element[@name='class']" location="class">
		<stereotype name="Entity">
			<generator canonicalName="org.dentaku.gentaku.cartridge.jdo.EntityGenerator"/>
		</stereotype>
	</element>
	<element path="/xs:schema/xs:element[@name='field']" location="field"/>
</mapping>

=== codehaus/dentaku/tags/RELEASE-0.9/maven-gentaku-plugin/src/plugin-resources/cgen-plugin/template-resources/src/java/mapping.xml
<?xml version="1.0" encoding="UTF-8"?>
<mapping tagNameBase="org.dentaku.gentaku.jdo" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="gengenMapping.xsd">
	<generator name="entityGenerator" canonicalName="org.dentaku.gentaku.cartridge.entity.jdo.JDOEntityGenerator"/>
	<element path="/xs:schema/xs:element[@name='jdo']" location="root"/>
	<element path="/xs:schema/xs:element[@name='package']" location="package">
		<stereotype name="Package"/>
	</element>
	<element path="/xs:schema/xs:element[@name='class']" location="class">
		<stereotype name="Entity"/>
	</element>
	<element path="/xs:schema/xs:element[@name='field']" location="field"/>
</mapping>

=== codehaus/dentaku/trunk/dentaku-cartridge-generator/src/java/org/dentaku/gentaku/cartridge/entity/hibernate/mapping.xml
<?xml version="1.0" encoding="UTF-8"?>
<mapping tagNameBase="org.dentaku.gentaku.hibernate" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="gengenMapping.xsd">
    <element path="/xs:schema/xs:element[@name='hibernate-mapping']" location="root"/>
    <element path="/xs:schema/xs:element[@name='class']" location="class">
        <stereotype name="HibernateEntity"/>
    </element>
    <element path="/xs:schema/xs:element[@name='property']" location="field"/>
    <element path="/xs:schema/xs:element[@name='many-to-one']" location="field"/>
    <element path="/xs:schema/xs:element[@name='one-to-one']" location="field"/>
    <element path="/xs:schema/xs:element[@name='component']" location="field"/>
    <element path="/xs:schema/xs:element[@name='dynamic-component']" location="field"/>
    <element path="/xs:schema/xs:element[@name='properties']" location="field"/>
    <element path="/xs:schema/xs:element[@name='any']" location="field"/>
    <element path="/xs:schema/xs:element[@name='map']" location="field"/>
    <element path="/xs:schema/xs:element[@name='set']" location="field"/>
    <element path="/xs:schema/xs:element[@name='list']" location="field"/>
    <element path="/xs:schema/xs:element[@name='bag']" location="field"/>
    <element path="/xs:schema/xs:element[@name='idbag']" location="field"/>
    <element path="/xs:schema/xs:element[@name='array']" location="field"/>
    <element path="/xs:schema/xs:element[@name='primitive-array']" location="field"/>
    <element path="/xs:schema/xs:element[@name='query-list']" location="field"/>
</mapping>
